### ISSUE TITLE
dtype after upgrading to Python 3.11 and TF 2.12.1

### ISSUE THREAD

**Issue by lebence** [Ximilar-com/tf-image#9]
Yesterday I would like to try my code with Python 3.11 and TF 2.12.1. I'm using Python 3.8 and TF 2.10.1 as default, and there is everything OK.

 But after upgrading I got this error:
 
```python
File "/usr/local/lib/python3.11/dist-packages/tf_image/core/convert_type_decorator.py", line 15, in wrap  *
        bboxes_type = bboxes.dtype

AttributeError: 'float' object has no attribute 'dtype'
```

Does the repository work with Python 3.11 and TF 2.12.1? Do you know that?
